/*
 * Copyright (c) 2007 - 2009 NVIDIA Corporation.  All rights reserved.
 * 
 * NVIDIA Corporation and its licensors retain all intellectual property
 * and proprietary rights in and to this software and related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA Corporation is strictly prohibited.
 */

/**
 * nvboot_nand_local.h - Internal definitions for using Nand as a second level
 * boot device.
 */

#ifndef INCLUDED_NVBOOT_NAND_LOCAL_H
#define INCLUDED_NVBOOT_NAND_LOCAL_H

#if defined(__cplusplus)
extern "C"
{
#endif

/** 
 * These defines are as per Nand Flash spec's.
 */
#define NAND_DEVICE_READID_0_MAKER_CODE_RANGE 7:0
#define NAND_DEVICE_READID_0_DEVICE_CODE_RANGE 15:8
#define NAND_DEVICE_READID_0_PAGE_SIZE_RANGE 25:24
#define NAND_DEVICE_READID_0_BLOCK_SIZE_RANGE 29:28
#define NAND_DEVICE_READID_0_BUS_WIDTH_RANGE 30:30

#define NAND_DEVICE_READID2_0_IS_TOGGLE_RANGE 15:15
#define NAND_DEVICE_READID2_0_IS_EFNAND_RANGE 7:7
#define NAND_DEVICE_READID2_JEDEC_0_IS_TOGGLE_RANGE 1:1

#define NVBOOT_NAND_COMMAND_TIMEOUT_IN_US 100000
#define NVBOOT_NAND_READ_TIMEOUT_IN_US 500000
#define NVBOOT_NAND_2KB_PAGE_SIZE_IN_LOG2 11
#define NVBOOT_NAND_4KB_PAGE_SIZE_IN_LOG2 12
#define NVBOOT_NAND_8KB_PAGE_SIZE_IN_LOG2 13
#define NVBOOT_NAND_16KB_PAGE_SIZE_IN_LOG2 14

/// Max address cycles 7 used to support for future devices
#define NVBOOT_NAND_MAX_ADDRESS_CYCLES_SUPPORTED 7
/// Min clock divider supported.
#define NVBOOT_NAND_MIN_CLOCK_DIVIDER_SUPPORTED 1
/// Max clock divider supported.
#define NVBOOT_NAND_MAX_CLOCK_DIVIDER_SUPPORTED 127

/// These defines are needed for Nand Addressing.
#define NVBOOT_NAND_ADDR_REG_1_PAGE_OFFSET 16
#define NVBOOT_NAND_ADDR_REG_1_PAGE_MASK 0xFFFF
#define NVBOOT_NAND_ADDR_REG_2_PAGE_OFFSET 16
#define NVBOOT_NAND_BITS_PER_ADDRESS_REGISTER 32

/** 
 * These defines are as per Open Nand Flash Interface spec 1.0.
 */
#define NVBOOT_NAND_ONFI_SIGNATURE_BYTE0_OFFSET 0
#define NVBOOT_NAND_ONFI_SIGNATURE_BYTE1_OFFSET 1
#define NVBOOT_NAND_ONFI_SIGNATURE_BYTE2_OFFSET 2
#define NVBOOT_NAND_ONFI_SIGNATURE_BYTE3_OFFSET 3

#define NVBOOT_NAND_ONFI_PAGE_SIZE_BYTE0_OFFSET 80
#define NVBOOT_NAND_ONFI_PAGE_SIZE_BYTE1_OFFSET 81
#define NVBOOT_NAND_ONFI_PAGE_SIZE_BYTE2_OFFSET 82
#define NVBOOT_NAND_ONFI_PAGE_SIZE_BYTE3_OFFSET 83
#define NVBOOT_NAND_ONFI_PAGES_PER_BLOCK_BYTE0_OFFSET 92
#define NVBOOT_NAND_ONFI_PAGES_PER_BLOCK_BYTE1_OFFSET 93
#define NVBOOT_NAND_ONFI_PAGES_PER_BLOCK_BYTE2_OFFSET 94
#define NVBOOT_NAND_ONFI_PAGES_PER_BLOCK_BYTE3_OFFSET 95
#define NVBOOT_NAND_ONFI_CRC_BYTE0_OFFSET 254
#define NVBOOT_NAND_ONFI_CRC_BYTE1_OFFSET 255
#define NVBOOT_NAND_ONFI_MAX_REDUNDANT_PARAM_PAGES 3
#define NVBOOT_NAND_ONFI_PARAM_PAGE_SIZE 256
#define NVBOOT_NAND_ONFI_CRC16_INIT 0x4F4E
#define NVBOOT_NAND_ONFI_CRC16_ORDER 0x10
#define NVBOOT_NAND_ONFI_CRC16_POLYNOMIAL 0x8005
#define NVBOOT_NAND_ONFI_PARAM_BUF_SIZE 2048

// These dfines are as per Samsung EF Nand Flash Interface2.0/3.0 spec.
#define NVBOOT_EFNAND_PARAM_BUF_SIZE 512
#define NVBOOT_EFNAND_PAGE_SIZE_BYTE0_OFFSE 52
#define NVBOOT_EFNAND_PAGE_SIZE_BYTE1_OFFSE 53
#define NVBOOT_EFNAND_PAGE_SIZE_BYTE2_OFFSE 54
#define NVBOOT_EFNAND_PAGE_SIZE_BYTE3_OFFSE 55
#define NVBOOT_EFNAND_PAGES_PER_BLOCK_BYTE0_OFFSET 32
#define NVBOOT_EFNAND_PAGES_PER_BLOCK_BYTE1_OFFSET 33
#define NVBOOT_EFNAND_PAGES_PER_BLOCK_BYTE2_OFFSET 34
#define NVBOOT_EFNAND_PAGES_PER_BLOCK_BYTE3_OFFSET 35

#define NVBOOT_NAND_ONFI_ADDRESS_CYCLES_BYTE_OFFSET 101
#define NVBOOT_NAND_ONFI_REVISION_NUMBER_BYTE_OFFSET 4
#define NVBOOT_NAND_ONFI_BUS_WIDTH_BYTE_OFFSET 6
#define NVBOOT_NAND_ONFI_DDR_SUPPORT_BYTE_OFFSET 6
#define NVBOOT_NAND_ONFI_EZNAND_SUPPORT_BYTE_OFFSET 7
#define NVBOOT_NAND_ONFI_EZNAND_SUPPORT_AUTO_RETRIES_BYTE_OFFSET 115
#define NVBOOT_NAND_ONFI_SETFEATURE_CMD_SUPPORT_BYTE_OFFSET 8
#define NVBOOT_NAND_ONFI_ASYNC_TIMING_MODE_BYTE_OFFSET 141
#define NVBOOT_NAND_ONFI_SYNC_TIMING_MODE_BYTE_OFFSET 129
#define NVBOOT_NAND_ONFI_BUS_WIDTH_MASK 0x01
#define NVBOOT_NAND_ONFI_EZNAND_SUPPORT_MASK 0x02
#define NVBOOT_NAND_ONFI_EZNAND_SUPPORT_AUTO_RETRIES_MASK 0x01
#define NVBOOT_NAND_ONFI_DDR_SUPPORT_MASK 0x20
#define NVBOOT_NAND_ONFI_SETFEATURE_CMD_SUPPORT_MASK 0x04
#define NVBOOT_NAND_ONFI_SIGNATURE 0x49464E4F //IFNO --> "ONFI"
#define NVBOOT_NAND_JEDEC_SIGNATURE 0x434544454A //IFNO --> "JEDEC"

#if defined(__cplusplus)
}
#endif

#endif /* #ifndef INCLUDED_NVBOOT_NAND_LOCAL_H */
