    // Initialization code generated by tool warmboot_code_gen
    NvU32 initParsPllM[7];

    if (pData == NULL) return NvBootError_InvalidParameter; //this is inside tool generated code only because the if statement has be after initialisation above per armcc compilation to aid auto-integrate of boot software

    // Save PLLM parameters (restored from outside)
    initParsPllM[0] = pData->PllMInputDivider;
    initParsPllM[1] = pData->PllMFeedbackDivider;
    initParsPllM[2] = pData->PllMStableTime;
    initParsPllM[3] = pData->PllMSetupControl;
    initParsPllM[4] = pData->PllMPostDivider;
    initParsPllM[5] = pData->PllMKCP;
    initParsPllM[6] = pData->PllMKVCO;

    NvBootUtilMemcpy(pData, &initParams, sizeof(NvBootSdramParams));

    // Restore PLLM parameters
    pData->PllMInputDivider = initParsPllM[0];
    pData->PllMFeedbackDivider = initParsPllM[1];
    pData->PllMStableTime = initParsPllM[2];
    pData->PllMSetupControl = initParsPllM[3];
    pData->PllMPostDivider = initParsPllM[4];
    pData->PllMKCP = initParsPllM[5];
    pData->PllMKVCO = initParsPllM[6];

    // End of generated code by warmboot_code_gen
